version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: HexagFinanceMongo
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: HexagFinanceRabbitMq
    ports:
      - "5673:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbit_data:
